package com.lc.autoEntity;

import java.io.Serializable;

public class SongInfoPO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.Id
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.name
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.singers
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String singers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.singernames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String singernames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.albumnames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String albumnames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.tags
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.programname
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String programname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.movienames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String movienames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.source
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.timelong
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long timelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.hot
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Integer hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.versiontype
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Integer versiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.songid
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long songid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.soundType
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Integer soundtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.invalidatedate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long invalidatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.originalMark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Integer originalmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.hotLevel
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Integer hotlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.hasAudio
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Boolean hasaudio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.updatetime
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.isEnabled
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Boolean isenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.toneinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long toneinvalidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.ringinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long ringinvalidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.hdinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long hdinvalidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.playinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long playinvalidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.mvinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long mvinvalidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.isDAlbum
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Boolean isdalbum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.firstStartDate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long firststartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.firstEndDate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long firstenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.remark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.aliasNames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String aliasnames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.songinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private Long songinvalidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.movieRemark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String movieremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.songWriters
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String songwriters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.albumSingerNames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String albumsingernames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.resourceId
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.copyRightId
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String copyrightid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.price
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songinfo.lyric
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private String lyric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table songinfo
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.Id
     *
     * @return the value of songinfo.Id
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.Id
     *
     * @param id the value for songinfo.Id
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.name
     *
     * @return the value of songinfo.name
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.name
     *
     * @param name the value for songinfo.name
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.singers
     *
     * @return the value of songinfo.singers
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getSingers() {
        return singers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.singers
     *
     * @param singers the value for songinfo.singers
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setSingers(String singers) {
        this.singers = singers == null ? null : singers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.singernames
     *
     * @return the value of songinfo.singernames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getSingernames() {
        return singernames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.singernames
     *
     * @param singernames the value for songinfo.singernames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setSingernames(String singernames) {
        this.singernames = singernames == null ? null : singernames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.albumnames
     *
     * @return the value of songinfo.albumnames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getAlbumnames() {
        return albumnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.albumnames
     *
     * @param albumnames the value for songinfo.albumnames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setAlbumnames(String albumnames) {
        this.albumnames = albumnames == null ? null : albumnames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.tags
     *
     * @return the value of songinfo.tags
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.tags
     *
     * @param tags the value for songinfo.tags
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.programname
     *
     * @return the value of songinfo.programname
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getProgramname() {
        return programname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.programname
     *
     * @param programname the value for songinfo.programname
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setProgramname(String programname) {
        this.programname = programname == null ? null : programname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.movienames
     *
     * @return the value of songinfo.movienames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getMovienames() {
        return movienames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.movienames
     *
     * @param movienames the value for songinfo.movienames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setMovienames(String movienames) {
        this.movienames = movienames == null ? null : movienames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.source
     *
     * @return the value of songinfo.source
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.source
     *
     * @param source the value for songinfo.source
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.timelong
     *
     * @return the value of songinfo.timelong
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getTimelong() {
        return timelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.timelong
     *
     * @param timelong the value for songinfo.timelong
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setTimelong(Long timelong) {
        this.timelong = timelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.hot
     *
     * @return the value of songinfo.hot
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.hot
     *
     * @param hot the value for songinfo.hot
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.versiontype
     *
     * @return the value of songinfo.versiontype
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Integer getVersiontype() {
        return versiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.versiontype
     *
     * @param versiontype the value for songinfo.versiontype
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setVersiontype(Integer versiontype) {
        this.versiontype = versiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.songid
     *
     * @return the value of songinfo.songid
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getSongid() {
        return songid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.songid
     *
     * @param songid the value for songinfo.songid
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setSongid(Long songid) {
        this.songid = songid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.soundType
     *
     * @return the value of songinfo.soundType
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Integer getSoundtype() {
        return soundtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.soundType
     *
     * @param soundtype the value for songinfo.soundType
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setSoundtype(Integer soundtype) {
        this.soundtype = soundtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.invalidatedate
     *
     * @return the value of songinfo.invalidatedate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getInvalidatedate() {
        return invalidatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.invalidatedate
     *
     * @param invalidatedate the value for songinfo.invalidatedate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setInvalidatedate(Long invalidatedate) {
        this.invalidatedate = invalidatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.originalMark
     *
     * @return the value of songinfo.originalMark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Integer getOriginalmark() {
        return originalmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.originalMark
     *
     * @param originalmark the value for songinfo.originalMark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setOriginalmark(Integer originalmark) {
        this.originalmark = originalmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.hotLevel
     *
     * @return the value of songinfo.hotLevel
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Integer getHotlevel() {
        return hotlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.hotLevel
     *
     * @param hotlevel the value for songinfo.hotLevel
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setHotlevel(Integer hotlevel) {
        this.hotlevel = hotlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.hasAudio
     *
     * @return the value of songinfo.hasAudio
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Boolean getHasaudio() {
        return hasaudio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.hasAudio
     *
     * @param hasaudio the value for songinfo.hasAudio
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setHasaudio(Boolean hasaudio) {
        this.hasaudio = hasaudio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.updatetime
     *
     * @return the value of songinfo.updatetime
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.updatetime
     *
     * @param updatetime the value for songinfo.updatetime
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.isEnabled
     *
     * @return the value of songinfo.isEnabled
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Boolean getIsenabled() {
        return isenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.isEnabled
     *
     * @param isenabled the value for songinfo.isEnabled
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setIsenabled(Boolean isenabled) {
        this.isenabled = isenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.toneinvalidate
     *
     * @return the value of songinfo.toneinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getToneinvalidate() {
        return toneinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.toneinvalidate
     *
     * @param toneinvalidate the value for songinfo.toneinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setToneinvalidate(Long toneinvalidate) {
        this.toneinvalidate = toneinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.ringinvalidate
     *
     * @return the value of songinfo.ringinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getRinginvalidate() {
        return ringinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.ringinvalidate
     *
     * @param ringinvalidate the value for songinfo.ringinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setRinginvalidate(Long ringinvalidate) {
        this.ringinvalidate = ringinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.hdinvalidate
     *
     * @return the value of songinfo.hdinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getHdinvalidate() {
        return hdinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.hdinvalidate
     *
     * @param hdinvalidate the value for songinfo.hdinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setHdinvalidate(Long hdinvalidate) {
        this.hdinvalidate = hdinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.playinvalidate
     *
     * @return the value of songinfo.playinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getPlayinvalidate() {
        return playinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.playinvalidate
     *
     * @param playinvalidate the value for songinfo.playinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setPlayinvalidate(Long playinvalidate) {
        this.playinvalidate = playinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.mvinvalidate
     *
     * @return the value of songinfo.mvinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getMvinvalidate() {
        return mvinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.mvinvalidate
     *
     * @param mvinvalidate the value for songinfo.mvinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setMvinvalidate(Long mvinvalidate) {
        this.mvinvalidate = mvinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.isDAlbum
     *
     * @return the value of songinfo.isDAlbum
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Boolean getIsdalbum() {
        return isdalbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.isDAlbum
     *
     * @param isdalbum the value for songinfo.isDAlbum
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setIsdalbum(Boolean isdalbum) {
        this.isdalbum = isdalbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.firstStartDate
     *
     * @return the value of songinfo.firstStartDate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getFirststartdate() {
        return firststartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.firstStartDate
     *
     * @param firststartdate the value for songinfo.firstStartDate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setFirststartdate(Long firststartdate) {
        this.firststartdate = firststartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.firstEndDate
     *
     * @return the value of songinfo.firstEndDate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getFirstenddate() {
        return firstenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.firstEndDate
     *
     * @param firstenddate the value for songinfo.firstEndDate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setFirstenddate(Long firstenddate) {
        this.firstenddate = firstenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.remark
     *
     * @return the value of songinfo.remark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.remark
     *
     * @param remark the value for songinfo.remark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.aliasNames
     *
     * @return the value of songinfo.aliasNames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getAliasnames() {
        return aliasnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.aliasNames
     *
     * @param aliasnames the value for songinfo.aliasNames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setAliasnames(String aliasnames) {
        this.aliasnames = aliasnames == null ? null : aliasnames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.songinvalidate
     *
     * @return the value of songinfo.songinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public Long getSonginvalidate() {
        return songinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.songinvalidate
     *
     * @param songinvalidate the value for songinfo.songinvalidate
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setSonginvalidate(Long songinvalidate) {
        this.songinvalidate = songinvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.movieRemark
     *
     * @return the value of songinfo.movieRemark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getMovieremark() {
        return movieremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.movieRemark
     *
     * @param movieremark the value for songinfo.movieRemark
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setMovieremark(String movieremark) {
        this.movieremark = movieremark == null ? null : movieremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.songWriters
     *
     * @return the value of songinfo.songWriters
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getSongwriters() {
        return songwriters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.songWriters
     *
     * @param songwriters the value for songinfo.songWriters
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setSongwriters(String songwriters) {
        this.songwriters = songwriters == null ? null : songwriters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.albumSingerNames
     *
     * @return the value of songinfo.albumSingerNames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getAlbumsingernames() {
        return albumsingernames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.albumSingerNames
     *
     * @param albumsingernames the value for songinfo.albumSingerNames
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setAlbumsingernames(String albumsingernames) {
        this.albumsingernames = albumsingernames == null ? null : albumsingernames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.resourceId
     *
     * @return the value of songinfo.resourceId
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.resourceId
     *
     * @param resourceid the value for songinfo.resourceId
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setResourceid(String resourceid) {
        this.resourceid = resourceid == null ? null : resourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.copyRightId
     *
     * @return the value of songinfo.copyRightId
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getCopyrightid() {
        return copyrightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.copyRightId
     *
     * @param copyrightid the value for songinfo.copyRightId
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setCopyrightid(String copyrightid) {
        this.copyrightid = copyrightid == null ? null : copyrightid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.price
     *
     * @return the value of songinfo.price
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.price
     *
     * @param price the value for songinfo.price
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songinfo.lyric
     *
     * @return the value of songinfo.lyric
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public String getLyric() {
        return lyric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songinfo.lyric
     *
     * @param lyric the value for songinfo.lyric
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    public void setLyric(String lyric) {
        this.lyric = lyric == null ? null : lyric.trim();
    }
}