package com.lc.autoDao;

import com.lc.autoEntity.SongInfoPO;

public interface SongInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songinfo
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songinfo
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    int insert(SongInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songinfo
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    int insertSelective(SongInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songinfo
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    SongInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songinfo
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    int updateByPrimaryKeySelective(SongInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songinfo
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(SongInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songinfo
     *
     * @mbggenerated Tue Jan 08 18:15:18 CST 2019
     */
    int updateByPrimaryKey(SongInfoPO record);
}