package com.lc.autoDao;

import com.lc.autoEntity.UserInfoPO;

public interface UserInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_copy
     *
     * @mbggenerated Sat Jun 23 21:55:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_copy
     *
     * @mbggenerated Sat Jun 23 21:55:38 CST 2018
     */
    int insert(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_copy
     *
     * @mbggenerated Sat Jun 23 21:55:38 CST 2018
     */
    int insertSelective(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_copy
     *
     * @mbggenerated Sat Jun 23 21:55:38 CST 2018
     */
    UserInfoPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_copy
     *
     * @mbggenerated Sat Jun 23 21:55:38 CST 2018
     */
    int updateByPrimaryKeySelective(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_copy
     *
     * @mbggenerated Sat Jun 23 21:55:38 CST 2018
     */
    int updateByPrimaryKey(UserInfoPO record);
}